services:
  sign_service:
    image: xhs-extract-sign_service:latest
    container_name: sign_service
    command: node sign_service.js
    ports:
      - "3001:3001"
    volumes:
      - .:/app

  parse_xhs:
    image: xhs-extract-parse_xhs:latest
    container_name: parse_xhs
    command: node parse_xhs.js
    ports:
      - "3002:3002"
    volumes:
      - .:/app