version: '3.8'
services:
  sign_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sign_service
    command: node sign_service.js
    ports:
      - "3001:3001"
    volumes:
      - .:/app

  parse_xhs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parse_xhs
    command: node parse_xhs.js
    ports:
      - "3002:3002"
    volumes:
      - .:/app